kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: mem-ijt
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: details
  mode: all
  stressors:
    memory:
      workers: 5
      size: 256MB
