kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: zzkinjection
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: pod_name
  mode: all
  value: '20'
  action: pod-kill