apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.4.1
  count: 1
  elasticsearchRef:
    name: quickstart
    namespace: elastic-system
  config:
    csp.strict: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    