kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: cpu-hog
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: ratings
  mode: all
  stressors:
    cpu:
      workers: 5
      load: 100
