kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: hip-pod-kill
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: currencyservice
  mode: all
  action: pod-kill
